sudo: required
language: node_js
node_js:
  - "16"

services:
  - docker

before_install:
  - docker build -t wahlbergf100/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wahlbergf100/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-west-2-537923170705"
  bucket_path: "frontend"
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
