sudo: required
language: node_js
node_js:
  - "16"

services:
  - docker

before_install:
  - docker build -t wahlbergf100/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wahlbergf100/docker-react npm run test
